---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: comfyui-sa
  namespace: default
  labels:
    app: comfyui
  annotations:
    # This SA will be associated to an IAM Role (via EKS Pod Identity)
    # that grants CloudWatch PutMetricData permission for namespace "ComfyUI".

