---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: comfyui-sa
  namespace: default
  labels:
    app: comfyui
  annotations:
    # IRSA annotation for KEDA to use (KEDA requires IRSA, not native EKS Pod Identity)
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/ComfyUICloudWatchRole
    # This SA is also associated to the same IAM Role via EKS Pod Identity Association
    # for the ComfyUI pods themselves

