---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: open-gallery-files-pv-efs
spec:
  capacity:
    storage: 500Gi  # Arbitrary for EFS; billing is usage-based
  accessModes:
    - ReadWriteMany
  mountOptions:
    - tls
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    # If you use an Access Point, set volumeHandle to fs-xxxxxxxx::fsap-xxxxxxxx
    # Otherwise, set to just fs-xxxxxxxx
    volumeHandle: ${EFS_FILE_SYSTEM_ID}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-gallery-files-pvc-efs
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""  # Static provisioning (no StorageClass)
  resources:
    requests:
      storage: 500Gi
  volumeName: open-gallery-files-pv-efs

