---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keda-operator
  namespace: keda
  annotations:
    # IRSA annotation for KEDA Operator to read CloudWatch metrics in operator mode
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/ComfyUICloudWatchRole

